.......
js-tasks-ru/jsbasic-20220711_anagess pull request #11
Opened 2022-08-14 17:20 UTC by annaFarsh

2022-08-14 17:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-14 20:01 UTC, SinimaWath requested changes

2022-08-14 20:01 UTC, SinimaWath commented on 6-module/2-task/index.js
> +}
Давай попробуем соблюдать базовые советы по стилю кода. https://learn.javascript.ru/coding-style
Особенно отступы - они позволяет понять как используется блок кода.

2022-08-14 20:01 UTC, SinimaWath commented on 6-module/2-task/index.js
> +}
Так же в классах, имеет смысл функциональность разбивать на методы, к примеру в этой задаче можно сделать так:
```
class ProductCard() {
 constructor(product) {
   this.elem = this.#render();
   
   // const button = ....
   
   button.addEventListener('click', this.#onProductAddClick);
 }
 
 #render() { }
 
 #onProductAddClick = () => { }
}

```


Это нужно для того, чтобы лучше понимать как работает твой класс/компонент. К примеру, видим что метод : `#render` - отвечает за формирование DOM, а метод: `#onProductAddClick` - за обработку нажатия по кнопке.

2022-08-14 20:01 UTC, SinimaWath commented on 6-module/3-task/index.js
> + constructor(slides) {
Давай тут тоже попробуем:
- Поправить отступы
- Разбить на базовые методы: `#render`, `#onLeftArrowClick`, `#onRightArrowClick`, `#onProductAddClick`, и их заиспользовать в конструкторе

2022-08-16 12:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-17 12:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-08-18 09:36 UTC, SinimaWath approved these changes

2022-08-18 09:37 UTC, merged