с
js-tasks-ru/jsbasic-20220711_anagess pull request #7
Opened 2022-08-04 12:38 UTC by annaFarsh

2022-08-04 12:39 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-05 13:13 UTC, SinimaWath requested changes

2022-08-05 13:13 UTC, SinimaWath commented on 5-module/1-task/index.js
> +myButt.onclick = function() {
Нужно использовать let/const

2022-08-05 13:13 UTC, SinimaWath commented on 5-module/2-task/index.js
> +div = togButt.nextElementSibling
Нужно использовать let/const

2022-08-05 13:13 UTC, SinimaWath commented on 5-module/2-task/index.js
> +function onClickHidden() {
Давай попробуем использовать стрелочную функцию

2022-08-05 13:13 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  if(positionLenta<3){
А что если, будет больше 4 елементов? Это тоже надо поддержать

2022-08-07 15:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-09 11:49 UTC, SinimaWath approved these changes

2022-08-09 11:49 UTC, merged